# Competencia en Kaggle: Titanic: Machine Learning from Disaster

# 1. Crea una cuenta en Kaggle https://www.kaggle.com/

# 2. Ejecuta las celdas 

In [1]:
import pandas as pd

train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')
validate = pd.read_csv('gender_submission.csv')

# Drop features-... is this good?

In [2]:
train = train.drop(['Name','SibSp','Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],axis=1)
test = test.drop(['Name','SibSp','Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],axis=1)

train.head(10)

PassengerId  Survived  Pclass     Sex   Age
0            1         0       3    male  22.0
1            2         1       1  female  38.0
2            3         1       3  female  26.0
3            4         1       1  female  35.0
4            5         0       3    male  35.0
5            6         0       3    male   NaN
6            7         0       1    male  54.0
7            8         0       3    male   2.0
8            9         1       3  female  27.0
9           10         1       2  female  14.0

# Sex mapping 1 - male, 0 - female

In [3]:
train['Sex_binary']=train['Sex'].map({'male':1,'female':0})
test['Sex_binary']=test['Sex'].map({'male':1,'female':0})


# Age cleaning

In [4]:
train['Age'] = train['Age'].fillna(0)
test['Age'] = test['Age'].fillna(0)

In [5]:
features = ['Pclass','Age','Sex_binary']
target = 'Survived'

In [6]:
train[features].head(3)

Pclass   Age  Sex_binary
0       3  22.0           1
1       1  38.0           0
2       3  26.0           0

In [7]:
import numpy as np

In [8]:
X_train = np.array(train[features])
X_train

array([[ 3., 22.,  1.],
       [ 1., 38.,  0.],
       [ 3., 26.,  0.],
       ...,
       [ 3.,  0.,  0.],
       [ 1., 26.,  1.],
       [ 3., 32.,  1.]])

In [9]:
y_train = np.array(train[target])
y_train = y_train.reshape(-1,1)
y_train

array([[0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
    

In [10]:
# Import keras modules
from keras.models import Sequential
from keras.layers import Dense
from keras.initializers import glorot_normal

/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [11]:
model = Sequential()
model.add(Dense(1, input_dim=3, activation='relu', kernel_initializer="uniform"))
model.add(Dense(1, activation='sigmoid', kernel_initializer="uniform"))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [12]:
model.fit(X_train, y_train, epochs=1, batch_size=10)

Epoch 1/1
891/891 [==============================] - 0s 447us/step - loss: 0.6831 - acc: 0.6162


In [13]:
X_test = np.array(test[features])
X_test

array([[ 3. , 34.5,  1. ],
       [ 3. , 47. ,  0. ],
       [ 2. , 62. ,  1. ],
       ...,
       [ 3. , 38.5,  1. ],
       [ 3. ,  0. ,  1. ],
       [ 3. ,  0. ,  1. ]])

In [14]:
predicciones = model.predict(X_test)
print(predicciones)


[[0.4361114 ]
 [0.42074227]
 [0.3993192 ]
 [0.446444  ]
 [0.4551146 ]
 [0.46445894]
 [0.44405267]
 [0.44840106]
 [0.46066296]
 [0.45474404]
 [0.48396254]
 [0.42151275]
 [0.45488328]
 [0.39797962]
 [0.4218772 ]
 [0.4529212 ]
 [0.43599665]
 [0.45474404]
 [0.448195  ]
 [0.42346847]
 [0.40930027]
 [0.47141513]
 [0.4868944 ]
 [0.4558985 ]
 [0.4205149 ]
 [0.41494164]
 [0.4562692 ]
 [0.4526665 ]
 [0.42834023]
 [0.48396254]
 [0.4155068 ]
 [0.45116684]
 [0.4399181 ]
 [0.48573148]
 [0.44345346]
 [0.45821008]
 [0.48573148]
 [0.4565007 ]
 [0.4492076 ]
 [0.48396254]
 [0.42993772]
 [0.48512518]
 [0.42720076]
 [0.44462734]
 [0.42460537]
 [0.4492076 ]
 [0.4228759 ]
 [0.48396254]
 [0.40426716]
 [0.43579185]
 [0.45174325]
 [0.44701928]
 [0.45846528]
 [0.44796425]
 [0.48454377]
 [0.47002292]
 [0.43542442]
 [0.4492076 ]
 [0.48396254]
 [0.4369367 ]
 [0.46029168]
 [0.44012332]
 [0.4589038 ]
 [0.4551146 ]
 [0.46700764]
 [0.48631293]
 [0.46066296]
 [0.4201508 ]
 [0.44207475]
 [0.40426716]
 [0.45234454]
 [0.45

In [15]:
predicciones = predicciones.tolist()

In [16]:
pre = pd.Series(predicciones)
validate['prediccion'] = pre
validate['prediccion'] = validate['prediccion'].str.get(0)
validate

PassengerId  Survived  prediccion
0            892         0    0.436111
1            893         1    0.420742
2            894         0    0.399319
3            895         0    0.446444
4            896         1    0.455115
5            897         0    0.464459
6            898         1    0.444053
7            899         0    0.448401
8            900         1    0.460663
9            901         0    0.454744
10           902         0    0.483963
11           903         0    0.421513
12           904         1    0.454883
13           905         0    0.397980
14           906         1    0.421877
15           907         1    0.452921
16           908         0    0.435997
17           909         0    0.454744
18           910         1    0.448195
19           911         1    0.423468
20           912         0    0.409300
21           913         0    0.471415
22           914         1    0.486894
23           915         0    0.455898
24           916         1    0.420515
25           917         0    0.414942
26           918         1    0.456269
27           919         0    0.452666
28           920         0    0.428340
29           921         0    0.483963
..           ...       ...         ...
388         1280         0    0.454744
389         1281         0    0.475594
390         1282         0    0.453128
391         1283         1    0.416435
392         1284         0    0.465849
393         1285         0    0.419584
394         1286         0    0.443684
395         1287         1    0.461820
396         1288         0    0.450591
397         1289         1    0.420515
398         1290         0    0.453359
399         1291         0    0.440927
400         1292         1    0.445202
401         1293         0    0.431879
402         1294         1    0.456269
403         1295         0    0.461448
404         1296         0    0.425606
405         1297         0    0.456707
406         1298         0    0.452551
407         1299         0    0.416072
408         1300         1    0.485731
409         1301         1    0.481545
410         1302         1    0.485731
411         1303         1    0.435562
412         1304         1    0.446813
413         1305         0    0.483963
414         1306         1    0.432817
415         1307         0    0.430623
416         1308         0    0.483963
417         1309         0    0.483963

[418 rows x 3 columns]

In [17]:
coincidencias = []
for dato in validate.prediccion:
    if dato >= 0.5:
        coincidencias.append(1)
    else:
        coincidencias.append(0)
validate['final'] = coincidencias
validate

PassengerId  Survived  prediccion  final
0            892         0    0.436111      0
1            893         1    0.420742      0
2            894         0    0.399319      0
3            895         0    0.446444      0
4            896         1    0.455115      0
5            897         0    0.464459      0
6            898         1    0.444053      0
7            899         0    0.448401      0
8            900         1    0.460663      0
9            901         0    0.454744      0
10           902         0    0.483963      0
11           903         0    0.421513      0
12           904         1    0.454883      0
13           905         0    0.397980      0
14           906         1    0.421877      0
15           907         1    0.452921      0
16           908         0    0.435997      0
17           909         0    0.454744      0
18           910         1    0.448195      0
19           911         1    0.423468      0
20           912         0    0.409300      0
21           913         0    0.471415      0
22           914         1    0.486894      0
23           915         0    0.455898      0
24           916         1    0.420515      0
25           917         0    0.414942      0
26           918         1    0.456269      0
27           919         0    0.452666      0
28           920         0    0.428340      0
29           921         0    0.483963      0
..           ...       ...         ...    ...
388         1280         0    0.454744      0
389         1281         0    0.475594      0
390         1282         0    0.453128      0
391         1283         1    0.416435      0
392         1284         0    0.465849      0
393         1285         0    0.419584      0
394         1286         0    0.443684      0
395         1287         1    0.461820      0
396         1288         0    0.450591      0
397         1289         1    0.420515      0
398         1290         0    0.453359      0
399         1291         0    0.440927      0
400         1292         1    0.445202      0
401         1293         0    0.431879      0
402         1294         1    0.456269      0
403         1295         0    0.461448      0
404         1296         0    0.425606      0
405         1297         0    0.456707      0
406         1298         0    0.452551      0
407         1299         0    0.416072      0
408         1300         1    0.485731      0
409         1301         1    0.481545      0
410         1302         1    0.485731      0
411         1303         1    0.435562      0
412         1304         1    0.446813      0
413         1305         0    0.483963      0
414         1306         1    0.432817      0
415         1307         0    0.430623      0
416         1308         0    0.483963      0
417         1309         0    0.483963      0

[418 rows x 4 columns]

In [18]:
coincide = 0
coincide = sum(validate['Survived'] == validate['final'])
print(coincide/ len(validate))


match = 0
nomatch = 0
for val in validate.values:
    if val[1] == val[3]:
        match = match +1
    else:
        nomatch = nomatch +1
print(match/len(validate))

0.6363636363636364
0.6363636363636364


In [19]:
toKaggle = pd.DataFrame({'PassengerId':validate['PassengerId'],
                         'Survived':validate['final']})

toKaggle.head()

PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         0

# output file with your prediction

In [20]:
from datetime import datetime
archivo = 'TitanicPred.csv'

toKaggle.to_csv(archivo,index=False)

print('Creado: ' + archivo)

Creado: TitanicPred.csv
